export const products = [
  {
    id: 1,
    title: "Camiseta Tampa Bay Buccaneers",
    price: 70,
    stock: 3,
    description: "Camiseta futbol americano (Tom Brady)",
    category: "NFL",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825030/Pagina%20Coder/tampa-bay-buccaneers-camiseta-de-futbol-americano-del-partido-nino-a-62TKXr_hhq7dc.jpg",
  },

  {
    id: 2,
    title: "Camiseta Atlanta Falcons",
    price: 95,
    stock: 5,
    description: "Camiseta futbol americano (Todd Gurley II)",
    category: "NFL",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678893467/Pagina%20Coder/atlanta-falcons-camiseta-de-futbol-americano-4QsJQT_yus7pw.jpg",
  },

  {
    id: 3,
    title: "Camiseta Chicago Bears",
    price: 70,
    stock: 5,
    description: "Camiseta futbol americano (Khalil Mack)",
    category: "NFL",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825108/Pagina%20Coder/chicago-bears-camiseta-de-futbol-americano-del-partido-nino-a-Gbr8XS_q1xiq5.jpg",
  },

  {
    id: 4,
    title: "Camiseta Seattle Seahawks",
    price: 140,
    stock: 5,
    description: "Camiseta futbol americano (Russell Wilson)",
    category: "NFL",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825130/Pagina%20Coder/seattle-seahawks-vapor-untouchable-camiseta-limited-de-futbol-americano-Rl83v5_hpqodr.jpg",
  },

  {
    id: 5,
    title: "Camiseta Houston Texans",
    price: 95,
    stock: 6,
    description: "Camiseta futbol americano (Deshaun Watson)",
    category: "NFL",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825170/Pagina%20Coder/houston-texans-camiseta-de-futbol-americano-4k2PTm_jsz2or.jpg",
  },

  {
    id: 6,
    title: "Camiseta Denver Broncos",
    price: 95,
    stock: 4,
    description: "Camiseta futbol americano (Phillip Lindsay)",
    category: "NFL",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825204/Pagina%20Coder/denver-broncos-camiseta-de-futbol-americano-LPgqDr_vjsrpj.jpg",
  },

  {
    id: 7,
    title: "Camiseta Chicago Bulls",
    price: 100,
    stock: 5,
    description: "Camiseta Jordan Dri-FIT NBA Swingman (DeMar DeRozan)",
    category: "NBA",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678894005/Pagina%20Coder/chicago-bulls-statement-edition-camiseta-jordan-dri-fit-nba-swingman-lQp2Zm_gv8qxt.jpg",
  },

  {
    id: 8,
    title: "Camiseta Nets Brooklyn",
    price: 140,
    stock: 6,
    description: "Camiseta Nike Dri-FIT (Kevin Durant)",
    category: "NBA",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825248/Pagina%20Coder/kevin-durant-nets-camiseta-dri-fit-nba-6P8Qrv_j3ccoi.jpg",
  },

  {
    id: 9,
    title: "Camiseta Maverick Dallas",
    price: 140,
    stock: 6,
    description: "Camiseta Nike Dri-FIT (Luka Dončić)",
    category: "NBA",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825266/Pagina%20Coder/luka-doncic-mavericks-camiseta-dri-fit-nba-cxdZfk_gqwuob.jpg",
  },

  {
    id: 10,
    title: "Camiseta Lakers Los Angeles",
    price: 100,
    stock: 3,
    description: "Camiseta Jordan Dri-FIT NBA Swingman (LeBron James)",
    category: "NBA",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825322/Pagina%20Coder/los-angeles-lakers-statement-edition-camiseta-jordan-dri-fit-nba-swingman-TzFHMn_kkqtdl.jpg",
  },

  {
    id: 11,
    title: "Camiseta Heat Miami",
    price: 100,
    stock: 5,
    description: "Camiseta Jordan Dri-FIT NBA Swingman (Jimmy Butler)",
    category: "NBA",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825361/Pagina%20Coder/jimmy-butler-miami-heat-city-edition-camiseta-dri-fit-nba-swingman-wqzTHX_pepyqy.jpg",
  },

  {
    id: 12,
    title: "Camiseta Celtics Boston",
    price: 100,
    stock: 5,
    description: "Camiseta Jordan Dri-FIT NBA Swingman (Jayson Tatum)",
    category: "NBA",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825430/Pagina%20Coder/boston-celtics-icon-edition-2022-23-camiseta-dri-fit-nba-swingman-VDXm28_mbgnet.jpg",
  },
  {
    id: 13,
    title: "Camiseta Yankees New York",
    price: 135,
    stock: 5,
    description: "Camiseta Nike Beisbol (John Donaldson)",
    category: "MLB",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825500/Pagina%20Coder/jersey-de-b_C3_A9isbol-replica-mlb-new-york-yankees-josh-donaldson-0lt9SJ_d90pty.jpg",
  },
  {
    id: 14,
    title: "Camiseta Blue Jays Toronto",
    price: 135,
    stock: 5,
    description: "Camiseta Nike Beisbol (Matt Chapman)",
    category: "MLB",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825515/Pagina%20Coder/camiseta-de-b_C3_A9isbol-replica-mlb-toronto-blue-jays-matt-chapman-xv1Rqj_uol2qf.jpg",
  },
  {
    id: 15,
    title: "Camiseta Dodgers Brooklyn",
    price: 115,
    stock: 5,
    description: "Camiseta Nike Beisbol",
    category: "MLB",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825537/Pagina%20Coder/camiseta-de-b_C3_A9isbol-cooperstown-mlb-brooklyn-dodgers-MmKFjL_ad2w24.jpg",
  },
  {
    id: 16,
    title: "Camiseta Braves Atlanta",
    price: 135,
    stock: 7,
    description: "Camiseta Nike Beisbol (Matt Olson)",
    category: "MLB",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825554/Pagina%20Coder/jersey-de-b_C3_A9isbol-replica-mlb-atlanta-braves-matt-olson-lT8Mjt_jeuulz.jpg",
  },
  {
    id: 17,
    title: "Camiseta Pirates Pittsburgh",
    price: 115,
    stock: 5,
    description: "Camiseta Nike Beisbol",
    category: "MLB",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678894226/Pagina%20Coder/camiseta-de-b_C3_A9isbol-replica-mlb-pittsburgh-pirates-5F1gKk_gaxvoz.jpg",
  },
  {
    id: 18,
    title: "Camiseta Padres San Diego",
    price: 135,
    stock: 4,
    description: "Camiseta Nike Beisbol (Fernando Tatis Jr)",
    category: "MLB",
    img: "https://res.cloudinary.com/dnxtjocny/image/upload/v1678825592/Pagina%20Coder/mlb-san-diego-padres-fernando-tatis-jr-jersey-de-b_C3_A9isbol-replica-hC8bjf_nxov6v.jpg",
  },
  
];
